services:
  mysql_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: passport
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33062:3306

